### ISSUE TITLE
회원의 스케줄 변경 시 변경되는 시간 선택하는 화면 표현방식

### ISSUE THREAD

**Issue by choseongmin1997** [AllideaBridge/gymming_app#61]

**Comment by choseongmin1997** [comment]
![image](https://github.com/AllideaBridge/gymming_app/assets/55073966/2ec4282d-84fd-4235-a570-508f0a29c0d3)

- 현재 레슨 시간은 1시간 단위라고 가정한 경우, 불가능한 시간은 임의로 넣었음
- 현재처럼 선택 가능한 모든 시간이 다 나오는 경우, 실제로 해당 시간에 예약이 불가능해도 선택 가능하게 나온다.
  - ex) 09:30 부터 한 시간 동안 수업이 진행이 불가능하지만, 09:30 버튼은 열려 있음 
--> 차라리 한 시간 수업이 가능한 시간만 보여 주는게 더 낫지 않을까 하는 생각..?

밑에는 예약 가능한 시간만 보여준느 경우
![image](https://github.com/AllideaBridge/gymming_app/assets/55073966/00719096-ab63-4190-b8af-d258079d5698)

**Comment by SeongGwan-a** [comment]
음... 가능한 시간만 보여주는건 뭔가... 별로인데 다른 방법을 찾아보긴 해야할듯? ㅠㅠ
